spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: Niraj@123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8081